### PR TITLE
fix: optimized react for unnecessary renders

### LINKED ISSUE #119: React: useAutoAnimate causes unnecessary renders
Hi! 👋 
      
Firstly, thanks for your work on this awesome project! 🙂 This is such a slick way to add animation with almost no effort!

I noticed that `useAutoAnimate` returns a new `setEnabled` function every time it's called. This causes unnecessary renders (and effect calls) if other hooks depend on that function.

I believe the solution is to use `useCallback` so that `setEnabled` is not re-created unless it has to be. I used [patch-package](https://github.com/ds300/patch-package) to fix the issue locally - here is the diff that solved it for me:

```diff
diff --git a/node_modules/@formkit/auto-animate/react/index.mjs b/node_modules/@formkit/auto-animate/react/index.mjs
index 606d2da..387bf2a 100644
--- a/node_modules/@formkit/auto-animate/react/index.mjs
+++ b/node_modules/@formkit/auto-animate/react/index.mjs
@@ -1,4 +1,4 @@
-import { useRef, useState, useEffect } from 'react';
+import { useRef, useState, useEffect, useCallback } from 'react';
 import autoAnimate from '../index.mjs';
 
 /**
@@ -9,11 +9,11 @@ import autoAnimate from '../index.mjs';
 function useAutoAnimate(options) {
     const element = useRef(null);
     const [controller, setController] = useState();
-    const setEnabled = (enabled) => {
+    const setEnabled = useCallback((enabled) => {
         if (controller) {
             enabled ? controller.enable() : controller.disable();
         }
-    };
+    }, [controller]);
     useEffect(() => {
         if (element.current instanceof HTMLElement)
             setController(autoAnimate(element.current, options || {}));
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

### PR DESCRIPTION
**Pull request by limxingzhi**
This fixes #119 

- wrapped setEnabled around useCallback
- added options as useCallback dependency for element

### CODE REVIEW

File: src/react/index.ts [hunk 1]
```diff
@@ -20,14 +20,17 @@ export function useAutoAnimate<T extends Element>(
...
-      setController(undefined);
+      setController(undefined)
     }
-  }, [])
-  const setEnabled = (enabled: boolean) => {
-    if (controller) {
-      enabled ? controller.enable() : controller.disable()
-    }
-  }
+  }, [options])
```
Comment (drmercer) [inline src/react/index.ts:25]: This doesn't seem correct - if the `options` object is an object literal, then this will cause the `element` callback to be re-evaluated on every render

**Comment by royeden** [comment]
Hello!
I have a possible fix for this use case that handles the following:
* Use `useRef` to store the `controller` instead of `useState`, so the component doesn't re-render whenever a controller is set.
* Invokes `destroy` on the controller when the component is unmounted, as it's no longer needed.
* Uses `useCallback` to memoize everything and should be stable by manually setting the correct dependencies (sometimes React just needs this :disappointed: ).

How could I submit my additions here? Do I need to send a contribution to the patched branch?
